# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5724cd05-f1a0-4b43-b973-e0d7902da155";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5724cd05-f1a0-4b43-b973-e0d7902da155".device = "/dev/disk/by-uuid/5724cd05-f1a0-4b43-b973-e0d7902da155";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B27E-EFF1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a53d4aa0-0e45-494b-836b-d316366431b7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
